index:
    path: /
    controller: App\Controller\MainController::index
    methods: [GET]

delete:
    path: /delete
    controller: App\Controller\MainController::delete
    methods: [POST]

csv:
    path: /csv
    controller: App\Controller\MainController::csv
    methods: [GET]

query:
    path: /query
    controller: App\Controller\MainController::query
    methods: [GET]

register:
    path: /register
    controller: App\Controller\MainController::register
    methods: [POST]

logout:
    path: /logout
    methods: GET